### ISSUE TITLE
Add image to testimonial manually

### ISSUE THREAD

**Issue by lauraroverts** [akvo/Akvo-Sites-ZZ-Template#10]
Testimonials allow you to display a YouTube video and provide additional text. E.g. http://akvosites.akvo.org/video/insert-your-own-youtube-videos/ 

You now need to upload an image manually. Daan is looking into a way that a thumbnail or still of the YouTube video is featured as an image automatically.

**Comment by Lynngre** [comment]
Fixed but @lauraroverts could you confirm?

**Comment by lauraroverts** [comment]
confirmed
