### ISSUE TITLE
Widget box header

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#108]
@samvthom16 we're missing the option to keep the headers as shown here.
![screen shot 2016-06-13 at 15 37 03](https://cloud.githubusercontent.com/assets/2675262/16022929/a0b3948e-31ba-11e6-95d3-94a69add1952.png)

**Comment by samvthom16** [comment]
Currently the theme has header in the widget but has been hidden from the customiser menu.

**Comment by Lynngre** [comment]
Can we unhide it for users to select to be visible or not? or to use a plan 'tag' isntead such as 'blog', 'news' etc as per Washalliance issue?

**Comment by Lynngre** [comment]
#108 fixed & closed
