### ISSUE TITLE
Tags on widgets

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#109]
@samvthom16 we're missing the 'tags' ('blog', 'news', 'project') on the widget boxes as shown here, on the new theme.
![screen shot 2016-06-13 at 16 12 50](https://cloud.githubusercontent.com/assets/2675262/16022966/c4a78594-31ba-11e6-981f-e53526694e49.png)

**Comment by samvthom16** [comment]
@Lynngre the tags and the header are the same or if kept separate will have redundant information

**Comment by Lynngre** [comment]
@samvthom16  the header as in the 'banner' across you mean?  Let's see how that looks for WashALliance as they're specifically asking for these instead of the 'banner' style header.

**Comment by Lynngre** [comment]
#109 fixed & closed
