### ISSUE TITLE
Adding a Google map doesn't function

### ISSUE THREAD

**Issue by lauraroverts** [akvo/Akvo-Sites-ZZ-Template#12]
In e.g. http://akvosites.akvo.org/wp-admin/post.php?post=109&action=edit&lang=en there is a box where you've got the possibility to enter an address in order to show a Google Map at the frontend, showing this address on the map. 

![screen shot 2015-08-27 at 11 42 28](https://cloud.githubusercontent.com/assets/4179989/9517516/d3d275aa-4cb0-11e5-9189-35a2cc39c19e.png)

However, when I type in an address, it doesn't show me anything in the frontend. 

Daan (ZZ) is looking into this.

**Comment by Lynngre** [comment]
This is working now. @lauraroverts could you check this is what you need?  http://akvosites.akvo.org/address/

**Comment by lauraroverts** [comment]
confirmed
