### ISSUE TITLE
News item colouring

### ISSUE THREAD

**Issue by lauraroverts** [akvo/Akvo-Sites-ZZ-Template#13]
If I change the colour of the News item box, the colour doesn't change. It stays orange. 
When I change the colour of any other box, the colour changes. 

![screen shot 2015-08-27 at 11 47 56](https://cloud.githubusercontent.com/assets/4179989/9517613/86aa274a-4cb1-11e5-8656-74bb45ceecc5.png)

Daan (ZZ) is looking into this.

**Comment by Lynngre** [comment]
Fixed, @lauraroverts please confirm

**Comment by lauraroverts** [comment]
confirmed
