### ISSUE TITLE
Image widget - Siteorigin

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#130]
Siteorigin image widget - image title size & colour to be defined by user/theme  (set CSS to use theme colour here, will look at size)

**Comment by samvthom16** [comment]
The title is taking the h3 font-size.

**Comment by Lynngre** [comment]
#130 fixed & closed by using custom CSS /* Set SO image widget header size*/
.so-widget-sow-image h2 {
  	text-align: center;
    font-size: 18px !important;
}
