### ISSUE TITLE
Option to select projects/update via Data feed plugin by country

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#132]
Create the option for user to select to show only updates/projects by country/location.

Not sure how the lookup would work.  The location id is part of the data but not the corresponding country.  Keep a 'lookup' table pulled via api?

**Comment by Lynngre** [comment]
After speaking to @samvthom16 and @KasperBrandt this is more complicated than we thought. We need a lookup for the various location ids or lat/long of the project & then attach these to the updates.

**Comment by KasperBrandt** [comment]
@Lynngre Looking up projects by country should be easy ([All projects in the Netherlands](http://rsr.akvo.org/rest/v1/project/?filter={%27recipient_countries__country%27:%27NL%27})). Looking up project updates by country of the project as well ([All updates of projects in the Netherlands](http://rsr.akvo.org/rest/v1/project_update/?filter={%27project__recipient_countries__country%27:%27NL%27})). However, project updates by the country where the update has been placed is not possible (there's not enough data + only lat/long indeed).

**Comment by Lynngre** [comment]
Thanks @KasperBrandt will work with @samvthom16 on combining this with keyword to pull project by country for WA.

**Comment by Lynngre** [comment]
@samvthom16 could you look into this in more detail?  We need to be able to add project updates by 'project location' (so API call for all project updates by keyword or partnership by project location).

**Comment by Lynngre** [comment]
@samvthom16 have you had time to look at this as yet?

**Comment by samvthom16** [comment]
Example request that gets updates for projects in Nigeria that has Akvo as a partner:
http://rsr.akvo.org/rest/v1/project_update/?filter={'project__partners':42,'project__recipient_countries__country__in':['NG']}

To get the ID of an org you know the name of: http://rsr.akvo.org/rest/v1/organisation/?filter={'name':'Akvo'}

To get a list of orgs with a name that contains "kvo": http://rsr.akvo.org/rest/v1/organisation/?filter={'name__icontains':'kvo'}

**Comment by Lynngre** [comment]
@samvthom16 how do we pull a list of projects by keyword or organisation filtered by country/location?  We need to look at how we can show these in a meaningful way - 1. As we do currently in a 'card widget' where we could create a whole row or page of projects OR Project updates only in a specific country And 2. how we could display these points on a map with a option to drill down by going to the rsr.akvo.org page for the project or update.

**Comment by Lynngre** [comment]
RSR API now allows to pull correct location of project or update via API
