### ISSUE TITLE
Menu sub-sub level

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#138]
Hover over the additional level & colour changes to green/blue.  This should remain in the same colour settings as the site.

**Comment by samvthom16** [comment]
Has been fixed in this commit https://github.com/akvo/akvo-sites-zz-template/commit/a5f4160b80cf1c725c5245a554eff56ecfa2402f

**Comment by Lynngre** [comment]
#138 fixed & closed new theme
