### ISSUE TITLE
Twitter feed  - list

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#139]
Allow for embedding of Twitter feed via list (for example)

Embed twitter timeline/feed Sam to create test of https://dev.twitter.com/web/embedded-timelines/list

**Comment by samvthom16** [comment]
<a class="twitter-timeline"  href="https://twitter.com/search?q=WASHalliance" data-widget-id="750596169806458880">Tweets about WASHalliance</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by samvthom16** [comment]
Go to https://twitter.com/settings/widgets
Create the widget. Copy the html and js code to the WP Text widget.

**Comment by Lynngre** [comment]
#139 fixed & closed
