### ISSUE TITLE
Tablet responsiveness issues

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites-zz-template#14]
At a small screen or tablet: 

- Responsiveness carousel images & main blog story: shape of the images doesn't look nice at a certain level. 

![screen shot 2015-08-27 at 11 50 59](https://cloud.githubusercontent.com/assets/4179989/9517679/e911ff52-4cb1-11e5-90f6-2c6377ce02c0.png)

But when making the screen even smaller, you first see the image and then the textbox underneath each other, which looks good again. 

- Can’t flick through carousel on tablet. 

- On a table in portrait, the text in the carousel stays full length, even if the text is longer than the image. In internet browser on a computer or mobile phone, the text gets shortened and stacked so there it's not a problem. 

- Featured images in blogs and news items get pixelated on a tablet in portrait.

**Comment by tlandn** [comment]
Done , the slider image should be about 600 x 300
