### ISSUE TITLE
Add museo sans font

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#147]
For WASH Alliance child template only, set museo sans as default.

**Comment by Lynngre** [comment]
@samvthom16 Wash Alliance have now requested that in fact for their child theme Museo Sans should only be used for headers & Arial for text. Is it possible to update their child theme?

**Comment by samvthom16** [comment]
How about the navigation?

**Comment by Lynngre** [comment]
@samvthom16 good question. I'll get an answer as early as possible tomorrow morning.

**Comment by Lynngre** [comment]
Keep all titles in Museo Sans.

Keep navigation/menu in Museo sans 500

**Comment by Lynngre** [comment]
#147 fixed & closed for child theme
