### ISSUE TITLE
Card widgets are not displaying text

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#149]
The card widgets are not displaying any content/text besides the featured image on base template
![screen shot 2016-06-28 at 14 59 42](https://cloud.githubusercontent.com/assets/2675262/16416464/a21de4ee-3d42-11e6-821f-4dcd5d80f1ed.png)
.

**Comment by samvthom16** [comment]
@Lynngre Can you share the link?

Its working fine for the diverge theme http://diverge.akvotest.org/

**Comment by Lynngre** [comment]
It may already be fixed on test, if I see it again I'll drop a note here.

**Comment by Lynngre** [comment]
#149 fixed & closed

**Comment by Lynngre** [comment]
@samvthom16 this issue is still present for RSR updates which contain a video, News items & some blog posts.  Can we look at this urgently when you're back please?

![screen shot 2016-07-28 at 11 17 57](https://cloud.githubusercontent.com/assets/2675262/17207572/8773b8c8-54b5-11e6-85f3-825ec8bbf2ec.png)
![screen shot 2016-07-28 at 11 13 19](https://cloud.githubusercontent.com/assets/2675262/17207574/8c460dd8-54b5-11e6-847f-dd758ba5b9d1.png)
![screen shot 2016-07-28 at 11 13 13](https://cloud.githubusercontent.com/assets/2675262/17207583/91be294e-54b5-11e6-8331-9e75d4f7b594.png)
![screen shot 2016-07-28 at 11 20 20](https://cloud.githubusercontent.com/assets/2675262/17207591/9a2e58f6-54b5-11e6-87fc-ebbe5c0a928b.png)

**Comment by samvthom16** [comment]
@lynn please put in the url that has the same problem

**Comment by Lynngre** [comment]
http://newwashalliance.akvotest.org/news-page/  is an example.  It looks like the issue may be related to the post having an image inserted?

**Comment by samvthom16** [comment]
@Lynngre I fixed the issue here http://newwashalliance.akvotest.org/news-page/. The issue was with the excerpt plugin. Had to change the settings.
