### ISSUE TITLE
CSS styling 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites-zz-template#15]
- If I adjust a font in the customiser, it only changes at the homepage and blog page, not at the other pages. E.g. header homepage vs header other page
![screen shot 2015-08-27 at 11 56 39](https://cloud.githubusercontent.com/assets/4179989/9517808/be55bf3c-4cb2-11e5-9d06-a8ce712b6e16.png) 

![screen shot 2015-08-27 at 11 56 54](https://cloud.githubusercontent.com/assets/4179989/9517815/c35d347e-4cb2-11e5-818b-fc395279ab78.png)

- The colour of the 'active' tab can't be adjusted. Always stays green. E.g. see http://akvosites.akvo.org/general-information/number-of-columns/ and hover over 'general information' in the menu. 
![screen shot 2015-08-27 at 11 57 57](https://cloud.githubusercontent.com/assets/4179989/9517840/eb4f837e-4cb2-11e5-9f63-491ed0a3408f.png)

- Not possible to adjust the colour of the body text in the carousel. It stays black and is therefore difficult to read, depending on the background colour. 

![screen shot 2015-08-27 at 11 59 48](https://cloud.githubusercontent.com/assets/4179989/9517879/232b3dba-4cb3-11e5-886c-c8b7e688a66f.png)

**Comment by tlandn** [comment]
Hi @Lynngre  can you explain more about this:

 If I adjust a font in the customiser, it only changes at the homepage and blog page, not at the other pages. E.g. header homepage vs header other page 

I see 2 images but don't quite understand. Thanks.

**Comment by lauraroverts** [comment]
If I use http://akvosites.akvo.org/wp-admin/customize.php to adjust the colours of the fonts, background and items, I can basically adjust anything, except for the colour of the Active tab in the menu dropdown. So if you look at the screenshot below, you see I've clicked at 'How does it work' under 'General Information'. The menu bar shows a yellow colour when I hover over the submenu items. When I click on it, it turns green. I am able to change yellow into any other colour. But the green, the colour of the active tab, always stays green. I would like to be able to change this colour too. 

![screen shot 2015-12-07 at 14 46 03](https://cloud.githubusercontent.com/assets/4179989/11628329/461ecaf6-9cf1-11e5-99d3-ef0fc49c8729.png)

**Comment by Lynngre** [comment]
@tlandn point 1 & point 2 seem to have been fixed by other work we did on styling recently.

Could you check the last point only regarding colour of font.

**Comment by tlandn** [comment]
Done, please see http://i.imgur.com/b5AzNcn.png
