### ISSUE TITLE
Card widgets - video post type

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#150]
When a 'video' post type is selected no image/featured image is created/added to the widget box.  As seen here under 'video example'.

![screen shot 2016-06-28 at 14 33 31](https://cloud.githubusercontent.com/assets/2675262/16416490/bcc30e3c-3d42-11e6-9dcf-135f450deacf.png)

**Comment by Lynngre** [comment]
@samvthom16 this isn't working as exptected. When I go to add a video post via 'videos' in admin area, http://diverge.akvotest.org/video/testing-video-single-post/ the video is not appearing.

**Comment by samvthom16** [comment]
Just updated the code on the test server and is working fine.

**Comment by Lynngre** [comment]
@samvthom16 on test the video featured image is not displayed correctly.
![screen shot 2016-07-08 at 08 20 42](https://cloud.githubusercontent.com/assets/2675262/16679036/f1cb4db6-44e4-11e6-8d6d-3b59d095044e.png)

**Comment by samvthom16** [comment]
The problem is not with the videos. This is a general problem with the featured image. The reason why the image is being cropped is because of its fixed height.
