### ISSUE TITLE
New base theme: post title error

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#157]
Post titles are replaced with 'Water portal' and title of post is pushed to the right.  The example below is from the live server for afrialliancenew.akvotest.org

![post_titles_error](https://cloud.githubusercontent.com/assets/2675262/16561121/d8c5098c-41f7-11e6-929e-2799451e0aa5.png)

**Comment by samvthom16** [comment]
@Lynngre This has also been updated in the previous commit.

**Comment by Lynngre** [comment]
#157 fixed & closed
