### ISSUE TITLE
Deployment code

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#16]
Include under code (/var/akvo/akvosites/code/):
- [x] all loose *.php
- [x] wp-admin folder
- [x] wp-content:  all loose *.php, languages folder, themes folder, plugins folder

Do not include under code in Github:
- [x] Search-Replace-DB-3.1
- [x] wp-content: mu-plugins folder, upgrade folder, uploads folder

**Comment by Lynngre** [comment]
Linked to https://github.com/akvo/akvo-provisioning/issues/207

**Comment by Lynngre** [comment]
@peeb the template folder code/wp-content/theme/akvo-sites is greyed out.
@peeb wp-config.php should not appear in the 'code' folder on github.

**Comment by peeb** [comment]
@Lynngre can you close this issue when you're happy that everything is in the right place?
