### ISSUE TITLE
Menu bar to not extend beyond last menu item

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#161]
Do not extend the 'grey' beyond the last menu item.

![menubar](https://cloud.githubusercontent.com/assets/2675262/16584667/84fdc890-42bd-11e6-8601-9f867d5fc601.png)

**Comment by samvthom16** [comment]
@Lynngre changes to be made only in the child theme?

**Comment by Lynngre** [comment]
For now, if possible, yes.

**Comment by Lynngre** [comment]
#161 Fixed & closed
