### ISSUE TITLE
Add Maven Pro font

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#166]
Add Maven Pro (Google font) to WordPress &  allow selection via dropdown in fonts for theme customisation via 'customise'.

**Comment by Lynngre** [comment]
@samvthom16 I don't see the media library to single post or maven pro changes on the test server, would you load them there please before we decide to push to live?

**Comment by samvthom16** [comment]
Has been updated on the test server. The font change won't work for washalliance theme as museo is running in the child theme.

**Comment by Lynngre** [comment]
#166 fixed & closed
