### ISSUE TITLE
News, media library, videos, blog posts

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#168]
The old ZZ theme created pages automatically based on the selection of post type (created in the left admin menu).

The page would add all entries to a summary page in widgets such as http://newwashalliance.akvotest.org/news/

This functionality provides an easy way of creating a page of all your posts as they are updated. 

But as these pages are not configurable with the new Base theme & page builder these pages are not useful & are too static as they are.

Should we update these pages (if possible) to allow users to add rows/widgets on these pages additonally to what is auto-generated or do we just remove this feature & allow users the 'single post' widget option?

**Comment by Lynngre** [comment]
#166 add to this commit

**Comment by Lynngre** [comment]
@

**Comment by samvthom16** [comment]
This is a default functionality provided by wordpress which still exist in the new theme. The another workaround for better customizability would be the option to use the akvo-cards shortcode that would pull not only the rss feeds but other post types such as news, blog, videos, etc.

**Comment by Lynngre** [comment]
Let's chat about this after our holidays.

**Comment by Lynngre** [comment]
This is working now.
