### ISSUE TITLE
Akvo JSON data feed plugin

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#17]
The plugin was written by Kreablo specifically for pulling any data you would like from RSR using the API (it can be used for ANY API not just RSR).  

Z&Z have included the use of this plugin in the theme to allow for partners to show project update data widgets anywhere on the Akvo Site, as requested.

Right now the theme can only use a datafeed/slug with the name ‘rsr’ - this means that we can only use 1 datafeed/slug throughout the site and it always has to be called ‘rsr’.  

As the plugin allows you to add as many data feeds of different types/names as you would like (eg. you could pull project lists/project counts & update counts for a dashboard style layout with kpis/pull all info on a specific project, FLOW api data, twitter api data) it seems strange that the use of it should be so limited by the fact that it has been ‘hardcoded’ into the theme in such a specific way.

**Comment by Lynngre** [comment]
Partner team are now starting to require the Json Data plugin to work as expected (ie. to be allowed to add more than 1 data feed/slug at a time). 
Currently we are limited as per above as Z&Z hardcoded 1 datafeed in by name instead of utilising the plugin as intended.
@lauraroverts let me know who we can utilize re fixing the theme files for this is Z&Z are off the cards.

**Comment by AndreasJonsson** [comment]
Now there are two additional widgets:  A generic data feed widget with lots of configuration parameters exposed and a specialized rsr update widget.  It is possible to prepare a set of such specialized widget to support different data feeds.  (The generic widget is a bit harder to configure for the users, but always possible to use.)
