### ISSUE TITLE
Remove the down arrow on the menu

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#173]
Remove the down arrows on the menu item.  The sub-level horizontal arrows can remain.
![screen shot 2016-07-12 at 10 10 04](https://cloud.githubusercontent.com/assets/2675262/16759798/fcfb9f9c-4818-11e6-91e3-3dbcdec14373.png)

**Comment by samvthom16** [comment]
Have done this for the WA theme only.

**Comment by Lynngre** [comment]
Great thanks.
#173 fixed & closed

**Comment by Lynngre** [comment]
@samvthom16 it's been requested that we remove the down arrow on the menu for the base template as well (we've so far only removed it for the WA template).
