### ISSUE TITLE
Join us tab

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#178]
@samvthom16 for WashAlliance template only please update the 'join us' tab to be dark orange at all times instead of current 'light grey'.

When hovering ensure it's light orange as per example. Their 'dark orange' is R238 G116 B2  #EE7402

![screen shot 2016-07-18 at 16 22 09](https://cloud.githubusercontent.com/assets/2675262/16917942/f744d092-4d03-11e6-9d8a-32c57cc2596b.png)

**Comment by samvthom16** [comment]
Hello Lynn, there's no way to ensure that the menu item is 'join us' through css. There are not enough selectors available. 

If we can ensure that the 'join us' would be right at the end, then this can be possible. I can set the styling for the last menu item.

**Comment by samvthom16** [comment]
@Lynngre has been updated.

**Comment by Lynngre** [comment]
Custom css added to site.  #178 fixed & closed

nav ul.navbar-nav li.orange-bg{
	background-color: #ee7402;
  	
}
nav ul.navbar-nav li.orange-bg a{
	color: #FFF;
}
