### ISSUE TITLE
Adding iFrames

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#18]
The site editors need to be able to add iFrames from various different sources.  

Currently it is only possible to add iFrames correctly if the site with the content you want to display has some specific Javascript code added to it’s footer.  

This is not an option for us as firstly, we may not always have access to add the code to another website’s footer and secondly, our site editors can’t be expected to have to do this.  

They need it to be as simple as possible - maybe finding a way to just lay out the content in the theme correctly via the use of a Wordpress plugin such as ‘Advanced Iframe’ is an option?

**Comment by AndreasJonsson** [comment]
I don't believe there is any solution to this.  If the target site is setting the same origin http header, it is an instruction to the web browser to refuse embedding the page as an iframe.  This is a security feature to prevent click jacking attacks.  There shouldn't be any workarounds without cooperation from the target web site.  "Advanced Iframe" only works on pages in the same  domain as the target page, or with cooperation from the target web site.

**Comment by Lynngre** [comment]
@AndreasJonsson could you setup Akvopedia as a page for us on sites.akvotest.org so we can see how the Akvopedia 'gadget' needs to work?

**Comment by Lynngre** [comment]
#18 no longer relevant with new Base theme Summer 2016
