### ISSUE TITLE
Header.php showing incorrect site title

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#180]
https://github.com/akvo/akvo-sites-zz-template/blob/4d6682be4c8e8af9e82de2bd446f2a9ee54f8711/code/wp-content/themes/akvo-sites-new/header.php

line 8:    
<title>Akvo Sites Testing domain &#8211; Testing Akvo Sites new template</title>

This should show the REAL site's title dynamically.

Applies to new base theme as well as child theme for WA.

**Comment by Lynngre** [comment]
@samvthom16 fixed this temporarily by removing the text between the title tags but this will need to be fixed correctly as soon as you're back from holidays.

**Comment by samvthom16** [comment]
Will update the git asap. For the time being this should solve it:

<title><?php wp_title();?></title>
