### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#182]
After using the 'load more' button after a few rows the columns are no longer filled as expected.

http://newwashalliance.akvotest.org/news-page/

![screen shot 2016-07-27 at 10 48 03](https://cloud.githubusercontent.com/assets/2675262/17169430/b7c91cda-53e7-11e6-8262-b7eb53a95a00.png)

**Comment by samvthom16** [comment]
@Lynngre This was also fixed when the excerpt settings changed.

**Comment by Lynngre** [comment]
#182 fixed & closed
