### ISSUE TITLE
Akvo card tag for RSR updates

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#186]
![screen shot 2016-08-09 at 08 41 15](https://cloud.githubusercontent.com/assets/2675262/17506951/153b2442-5e0d-11e6-8f64-22aa91a6b3dc.png)
Either make this something which can be updated by the user or make it something generic - 'Project'.

**Comment by samvthom16** [comment]
Can be added through the shortcode [akvo-cards type=rsr type-text=Projects]
