### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#193]
Logos that are rectangular are not displaying correctly or large enough in the top left hand corner as they are being cropped.  We need these logos to span across further instead of cropping the image so dramatically.
For example:
![afriallianca_logo](https://cloud.githubusercontent.com/assets/2675262/17595306/c942a16e-5fec-11e6-922f-18696821e485.png)

**Comment by samvthom16** [comment]
@Lynngre Please share the link as well

**Comment by Lynngre** [comment]
afrialliancenew.akvotest.org/

**Comment by Lynngre** [comment]
Logo auto crops to 300px. Will be widened to allow for wider logos as there is plenty of space between the search box & the logo area.

**Comment by samvthom16** [comment]
Increasing the logo size displaces the search bar on the right. For us to go with the increased logo then the header design has to be changed.

**Comment by Lynngre** [comment]
This issue seems to be resolved for now, closing until further requests by partner.
