### ISSUE TITLE
News post type excerpts not shown

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#199]
http://afrialliancenew.akvotest.org/news/

![screen shot 2016-08-24 at 13 37 40](https://cloud.githubusercontent.com/assets/2675262/17929317/f68e9566-69ff-11e6-80c8-bb17d3b95840.png)

**Comment by samvthom16** [comment]
The conflict with the excerpt not being shown is when the site builder plugin is used. For work around use custom post excerpt field below the main text editor.

**Comment by Lynngre** [comment]
This is related to settings for the excerpt plugin - would it be possible to set a 'default' on activation of the plugin for the a new site?
