### ISSUE TITLE
Php error on benin-assainissement.akvosites.test.akvo-ops.org/

### ISSUE THREAD

**Issue by larsheemskerk** [akvo/Akvo-Sites-ZZ-Template#2]
When I customized the template via 'appearance' menu the following error appeared on the homepage:

Notice: Undefined index: columns in /var/akvo/akvosites/code/wp-content/themes/akvo-sites/lib/custom-widgets.php on line 52 Notice: Undefined index: type in /var/akvo/akvosites/code/wp-content/themes/akvo-sites/lib/custom-widgets.php on line 53

**Comment by Lynngre** [comment]
WP debugging was set to 'true' in wp-config.php.  
#2 fixed & closed
