### ISSUE TITLE
Script tag not working within text widget

### ISSUE THREAD

**Issue by samvthom16** [akvo/akvo-sites-zz-template#208]
Twitter widget for multiple search queries. Afrialliance needs twitter feeds for both @afrialliance1 and #afrialliance. 

Used the twitter widget referencing this https://github.com/akvo/akvo-sites-zz-template/issues/139 but the script tag gets stripped from the widget.

**Comment by samvthom16** [comment]
Used the same twitter widget here http://diverge.akvotest.org/ on the footer and is working fine.

**Comment by Lynngre** [comment]
Their are no plugins for Twitter feeds which allow both #search & @user, you need to use Twitter's own embedded timeline option as per screenshot.  

Twitter feed on AfriAlliance has both #search & @user now as per 2nd screenshot.. 

http://afrialliance.org/

Closing issue.
![screen shot 2016-09-26 at 10 54 18](https://cloud.githubusercontent.com/assets/2675262/18828488/719b401e-83d8-11e6-9e1c-506de2231b11.png)

![screen shot 2016-09-26 at 10 57 56](https://cloud.githubusercontent.com/assets/2675262/18828481/6a5992f6-83d8-11e6-9c49-8efb2543cab8.png)
