### ISSUE TITLE
Akvo theme card widget 'Read more' button

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#218]
Currently the 'Read more' button for the card widgets does not auto translate as the rest of the theme/WordPress does with the WPML translation plugin.  Card widgets are the boxes/widgets which are created automatically by the theme for things like 'News', 'Media library', RSR project updates, etc.

Instead of spending hours of coding trying to get it to work, we are going to:
1.  Allow users to update the text to what ever they like, thus allowing them to write it in French or use different wording if so required
2. Add the customisation option to the 'Card Widget' area under the 'customise' admin area
3. Ensure that 'Read more' is the default if nothing else is set
4. Ensure that we test length of text allowed & how it affects the appearance of the button & widget box

**Comment by Lynngre** [comment]
This code wasn't deployed on the 'intrusion' release v2.0.5 for some reason.  I can't see it on the server.

**Comment by samvthom16** [comment]
Default value for the button is not being set
<img width="892" alt="screen shot 2016-11-10 at 2 08 43 pm" src="https://cloud.githubusercontent.com/assets/1712132/20169745/3cdbb8c8-a74f-11e6-82c2-48f69071a9a9.png">
