### ISSUE TITLE
Widgets cutting off text

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#23]
Widgets are not displaying long text with 'more', and ignore the 'more' tag if added, so text is abruptly cut off. Applies to all menu items with widgets after 2nd main menu item.
<img width="1277" alt="screen shot 2015-09-29 at 15 54 13" src="https://cloud.githubusercontent.com/assets/2675262/10158781/8c6eedc6-6694-11e5-8165-6cb902d919c0.png">

**Comment by AndreasJonsson** [comment]
The theme is using the plugin 'advanced-excerpt' which can be configured in various ways on this page:

http://sites.akvotest.org/wp-admin/options-general.php?page=advanced-excerpt

It should not ignore manually added 'more' tags, unless the manual excerpt is too large to fit within the configured excerpt size (currently 21 words).

**Comment by AndreasJonsson** [comment]
Can I close this one?  I believe it is just a matter of configuring the 'advanced-excerpt' to your liking...
