### ISSUE TITLE
Card widgets - slow to load

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#238]
When testing Akvo sites loading time/speed it appears that the card widgets, whether set to pull data from RSR project updates via the JSON plugin data, or for a news article created locally too, it takes well over 1.5 - 2 seconds to load.  

![screen shot 2016-11-10 at 13 54 44](https://cloud.githubusercontent.com/assets/2675262/20177837/17065b26-a74f-11e6-9298-04fcb1bceb1c.png)
![screen shot 2016-11-10 at 13 54 56](https://cloud.githubusercontent.com/assets/2675262/20177840/1a0b1366-a74f-11e6-884b-5021d1bc8164.png)

**Comment by samvthom16** [comment]
Wordpress ajax functionality in the server itself is taking about 1.5 seconds to load.

**Comment by Lynngre** [comment]
@samvthom16 could you try this on the test server https://wordpress.org/plugins/heartbeat-control/

it blocks the admin-ajax.php but only in certain places, maybe we can get this to stop the slow loading of the cardwidgets?

**Comment by samvthom16** [comment]
To decrease the overload, light weight version of an ajax handler can be defined. 

https://coderwall.com/p/of7y2q/faster-ajax-for-wordpress

**Comment by Lynngre** [comment]
@samvthom16 could we try that on diverge.akvotest.org please?

**Comment by samvthom16** [comment]
#264 - increase the overall speed to make the card widgets load faster
