### ISSUE TITLE
Events plugin - widget

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#239]
Currently the 'events plugin' widget displays as follows:

![screen shot 2016-11-15 at 12 28 44](https://cloud.githubusercontent.com/assets/2675262/20304184/34fdd7ec-ab2f-11e6-9e99-30bf6c4fb231.png)

Content editors are adding the list manually via a text widget as not enough information is available in the 'Event' plugin widget itself.  Manual example below:

![screen shot 2016-11-15 at 12 24 11](https://cloud.githubusercontent.com/assets/2675262/20304398/493d6b18-ab30-11e6-9c31-ed4dd1a8cda2.png)

We would like them to utilise the 'events' plugin widget but they need the following changes.

Editors would like to display a list of 2 events:

- [x] Title of event is required
- [x] Date of event is required
- [x] Location country & city is required
- [x] Which partners are joining is required
- [ ] 'All events' button colour needs to be something we can change

This update is for all users on the new Akvo theme not only for AfriAlliance.

**Comment by Lynngre** [comment]
To allow for the 'meet' information of which partner will be there we need to add this option into the admin backend of the 'event' via custom fields.

- [ ] @samvthom16 will add a field with free text input
- [ ] This field will appear to the right of the 'venue' information as title 'meet' on the event's actual page eg http://afrialliance.org/event/un-climate-conference-cop22/
![screen shot 2016-11-16 at 13 48 01](https://cloud.githubusercontent.com/assets/2675262/20347970/b5b29632-ac03-11e6-8d72-f85b26207a21.png)

- [ ] This field will appear to the right of the 'venue' information as title 'meet' on the all events page eg. http://afrialliance.org/events/
![screen shot 2016-11-16 at 13 49 34](https://cloud.githubusercontent.com/assets/2675262/20347965/b08f384a-ac03-11e6-88b9-18a7e2b9d616.png)

**Comment by samvthom16** [comment]
Custom fields for partners in the events. 
[advanced-custom-field-export.xml.zip](https://github.com/akvo/akvo-sites-zz-template/files/596696/advanced-custom-field-export.xml.zip)

**Comment by Lynngre** [comment]
@samvthom16 could you check how we could limit the size of the event featured image from taking all the space when the widget is changed to 2 columns instead of 1?

![screen shot 2016-11-22 at 16 46 45](https://cloud.githubusercontent.com/assets/2675262/20530358/6665d330-b0d3-11e6-9b9b-c266b31b81b9.png)

Also, did we add a way to update/select the colour of the 'view all events' button?

**Comment by samvthom16** [comment]
@Lynngre the button color uses the default color uniformly selected from the customise.
