### ISSUE TITLE
Image rendering

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#28]
Images are not displayed correctly  http://snv.akvotest.org/benificiaries/

**Comment by Lynngre** [comment]
@AndreasJonsson Andreas you can see the same problem here http://sites.akvotest.org/2015/10/21/another-test-post/

**Comment by AndreasJonsson** [comment]
So, the issue is images in article texts, which are scaled to 100% of the article column width.  Since the height is set, only the width is scaled.

Am I correct:

* The image above the post should be scaled to 100% of the column width
* Other images should not be scaled (but maybe have a max-width).
* Other images should be centered or float to the left or right?  Or should they simply be left alone?  (I.e., no scaling and no positioning.)

**Comment by Lynngre** [comment]
update functions.php in theme folder to include, provides responsiveness & users don't need to mess around with image sizing:

add_filter( 'post_thumbnail_html', 'remove_width_attribute', 10 );
add_filter( 'image_send_to_editor', 'remove_width_attribute', 10 );

function remove_width_attribute( $html ) {
   $html = preg_replace( '/(width|height)="\d*"\s/', "", $html );
   return $html;
}

**Comment by AndreasJonsson** [comment]
It is better to add height: auto; to the css.  The height and width attributes should always be specified as a declaration of how large the source image actually is.

Also there are many pitfalls of using regular expressions like this, so I'd recommend avoiding this.

**Comment by Lynngre** [comment]
@AndreasJonsson  not sure what we should do here. 

Setting each image aspect, height/width is not going to work for our partners.  Most  native Wordpress themes don't stretch images out/seem to struggle with images the way this one does.

With Wordpress you can also usually go & 'create' different size images from the same image and crop the image to display the face at the top of the image instead of the stomach in middle of the image  - so you can create a thumbnail you could specifically use for a featured image.

With this theme installed I can go & crop the image to create a 'thumbnail' sized image but the thumbnail is never stored/never appears anywhere for selection when setting a featured image.

Can you check this post as an example:

http://sites.akvotest.org/2015/11/04/testing-after-deploying/

I've added a full size and medium size image in the post as well as a featured image which is on http://sites.akvotest.org

**Comment by Lynngre** [comment]
The cropped thumbnail definitely exists as I have the option to use it in a post as a normal image selecting 'thumbnail' (the option I don't get for a featured image).
It's horridly stretched of course.

http://sites.akvotest.org/blog/just-another-test/  (end of post)

**Comment by AndreasJonsson** [comment]
So, by using width: 100%; height: auto; you would get the same size on all images, although the resolution would be worse on smaller images.

It is possible to instead use max-width: 100%; height: auto; to have images displayed in their actual size, unless they are wider than the column, in which case they will be scaled.  (The aspect ratio should still be correct, though.)

**Comment by AndreasJonsson** [comment]
What is the status of this issue?  Is the fix with max-width: 100% acceptable?

**Comment by Lynngre** [comment]
It looks ok in the post itself now, but if I select a featured image for the post it's showing in the post itself again, which I thought we disabled.

**Comment by AndreasJonsson** [comment]
#29 was about hiding the featured image in the post.  It was closed, but I cannot see how the commits made under this issue are related to the featured image.

**Comment by Lynngre** [comment]
http://sites.akvotest.org/testing-images-18-nov - you can see what I mean here.

sorry yeah I got mixed up with that and updated the comment above.

**Comment by AndreasJonsson** [comment]
So, the featured image should be visibile, but not scale when it is smaller than the column width?  And maybe centered?  Then, maybe:

```css
.main-image {
	text-align: center;
	img {
		max-width: 100%;
		height: auto;
	}
}
```

**Comment by Lynngre** [comment]
Ok let's try that.
