### ISSUE TITLE
Remove featured image appearing in post

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#29]
We do not need the 'featured' image to appear at the top of each post. Is there a way to remove this/setting in the php files/?

**Comment by Lynngre** [comment]
http://sites.akvotest.org/2015/10/21/another-test-post/

**Comment by AndreasJonsson** [comment]
There is no setting.  It would be possible to add display: none to the style sheet.  But if you don't want a feature image, you could also simply not add any featured image to the post (or remove it from existing posts).  If the author have added a featured image, why hide it?

**Comment by Lynngre** [comment]
@AndreasJonsson we want a featured image as we want an image to show on the 'collected' page as here for example http://sites.akvotest.org/news/ but not in the post itself.

**Comment by Lynngre** [comment]
Ah we need to remove  else {
            the_post_thumbnail( 'large' );
          }
from content-single.php

**Comment by Lynngre** [comment]
Need to discuss this with the Akvo Sites team

**Comment by Lynngre** [comment]
https://github.com/akvo/akvo-sites-zz-template/pull/30
