### ISSUE TITLE
Duplicate content being shown on the card widgets

### ISSUE THREAD

**Issue by samvthom16** [akvo/akvo-sites-zz-template#297]
Offset counter for WP Query not being set

**Comment by Lynngre** [comment]
Still an issue it seems it wasn't just for 'news' but for all selections in single post widgets.

**Comment by Lynngre** [comment]
![screen shot 2017-05-31 at 12 31 31](https://cloud.githubusercontent.com/assets/2675262/26628168/4daf6f1c-45fd-11e7-97c9-d5890e0f3915.png)

**Comment by Lynngre** [comment]
Looks like a caching issue as fixed now, before I release could you check this @samvthom16 ?
