### ISSUE TITLE
Error on the Media Library page

### ISSUE THREAD

**Issue by larsheemskerk** [akvo/Akvo-Sites-ZZ-Template#3]
The following message appears when I visit the Media Library link: Fatal error: Call to undefined function wp_pagenavi() in /var/akvo/akvosites/code/wp-content/themes/akvo-sites/index.php on line 139  It doenst appear on the other pages probably because I manually added this link to the menu structure in the appearance tab. The error messages appears but I can just click through to the next page.

**Comment by larsheemskerk** [comment]
Error message also appears when I add the "cartes" and "videos" menu manually in the menu.

**Comment by Lynngre** [comment]
@larsheemskerk could you confirm this is fixed?

**Comment by larsheemskerk** [comment]
confirmed
