### ISSUE TITLE
Wandelenvoorwater.nl text outside of widget

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#344]
When the screen resolution is 1167x802 text in the box overlaps. So either we ensure that the text wraps or we get the responsiveness to work correctly. This fits into our general responsiveness issues, how do we ensure less standard resolutions display correctly.

![screen shot 2017-10-18 at 13 50 46](https://user-images.githubusercontent.com/2675262/31717316-a9abe8dc-b40b-11e7-8a10-e4ce1c923f22.png)

**Comment by samvthom16** [comment]
We could add ellipsis to all titles, like we do for titles in card widgets while pulling RSR information.
