### ISSUE TITLE
Akvopedia widget

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#36]
@AndreasJonsson the Akvopedia widget doesn't seem to allow 'click through' to Akvopedia (as per widget on sites.akvotest.org.

Also how do we frame this/add this widget to a new page/post in full content size?

**Comment by AndreasJonsson** [comment]
There is a parameter for this in the akvopedia gadget.  I've exposed it in the widget configuration.

You will also need a post type based on the akvopedia gadget if you want to use it in a post.

**Comment by Lynngre** [comment]
@AndreasJonsson is there a way to add/create a more elegant option or more user friendly way for people to be able to do this?  If we need to add code to the theme to make this useable, ie. custom types code into the theme could you please add this with easy options to add Akvopedia to a page/post or as a widget?

**Comment by AndreasJonsson** [comment]
Now I've also added a post type for the akvopedia widget.

@Lynngre Could you be more specific about what the difficulties are for the users?  Doesn't other widgets work the same way?

**Comment by Lynngre** [comment]
Do you have time for a call later today? Drop me a mail with a time that suits.

**Comment by Lynngre** [comment]
@AndreasJonsson it seems that when any new Akvopedia post is added the rewrite rules cache needs to be cleared by 'resaving' the permalinks?

http://sites.akvotest.org/akvopedia/_rooftop_rainwater_harvesting/#akvopedia:Water%20Portal%20/%20Rainwater%20Harvesting%20/%20Rooftop%20rainwater%20harvesting

I updated something on the link above and it only worked once I 'reset' the permanlink settings.

Is there any other way as clearing rewrite cache isn't a great option.

**Comment by Lynngre** [comment]
#36 if updates are required, better to recreate it or refresh permalinks. Fixed & closed.

**Comment by AndreasJonsson** [comment]
Sorry, I've missed your comment about needing to reset the permalinks above.  But this should not be necessary at all.  Because the "permalink settings" consists of a regexp that is installed to recognize posts of this particular type.  There is no additional settings installed for each new post.  So, the flushing the permalink cache only needs to be done when activating and deactivating the plugin.
