### ISSUE TITLE
Google fonts: Auto refresh

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#374]
Auto refresh to the Customise page once a new Google Font is loaded/publish is selected to ensure that font loads for selection.

**Comment by samvthom16** [comment]
Create custom control in WP Customise:
https://premium.wpmudev.org/blog/creating-custom-controls-wordpress-theme-customizer/
https://themetrust.com/how-to-create-custom-controls-for-wordpress-theme-customizer/
https://www.templatemonster.com/blog/create-control-wp-customizer/
http://ottopress.com/2012/making-a-custom-control-for-the-theme-customizer/

**Comment by samvthom16** [comment]
https://gist.github.com/ericandrewlewis/2310fd6d7dabf0696965
http://justintadlock.com/archives/2015/06/05/javascript-templating-in-the-wordpress-customizer
