### ISSUE TITLE
GDPR/Responsible data: login consent/text

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#378]
The login needs to be updated with an area of text including links to documents related to retention, use of personal data. Also explicit consent needs to be given for newsletters or product updates/contacts.

**Comment by samvthom16** [comment]
Wordpress now enables users to add privacy policy page. It can be set under Settings->Privacy

**Comment by Lynngre** [comment]
- [x] WordPress login needs tickbox for 'I have read and accept'  Akvo's Terms of Service (SaaS)
- [x] short text with url to Terms of service and url to privacy policy
- [x] Tickbox - should only be ticked once by a user
- [x] then greyed out/inactive from ticking again, but link to Terms of Service & privacy policy remain reachable from there.
- [x] we should store the date, time, url/site from which the acceptance was done. (ie. sites.akvo.org/wp-login.php or wp-admin.php)
- [x] if user has not selected, the empty box should be kept until they select the Terms of Service

**Comment by Lynngre** [comment]
Before releasing we need to add correct text/links.
