### ISSUE TITLE
Ultimate WP Query Search Filter

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#38]
Missing search buttonand the select box. May need some theme coding re setup here:  http://9-sec.com/

**Comment by Lynngre** [comment]
@tlandn so we need the UWPQSF plugin because the general WordPress search doesn't offer enough flexibility but it looks like the theme was not coded correctly to work with the UWPQSF shortcodes.

It looks like this right now, you can see there's no search button and no responsiveness http://sites.akvotest.org/media/:

![screen shot 2015-12-02 at 15 18 36](https://cloud.githubusercontent.com/assets/2675262/11533173/9ed174a6-9908-11e5-9944-2c6fc060ea5c.png)


So this is basically what the filter should look like:  http://sites.akvotest.org/testing-wpq-search-form/
![screen shot 2015-12-02 at 15 18 29](https://cloud.githubusercontent.com/assets/2675262/11533128/6e1b5e3a-9908-11e5-8a72-cb003fde4288.png)


BUT as a widget on which ever page of the theme we would like instead of on it's own page.

The only way that the previous coders made available for users was via 'customize' under 'Appearance/themes'.  Under 'Results filters' to the left. You can only add the numbers of the shortcode so it's impossible to add parameters such as 'button=1'.

![screen shot 2015-12-02 at 15 20 01](https://cloud.githubusercontent.com/assets/2675262/11533146/7e3ab072-9908-11e5-9702-08993961933a.png)


Info on the plugin:  http://9-sec.com/2014/01/ultimate-wp-query-search-filter/

**Comment by tlandn** [comment]
Done

http://sites.akvotest.org/media/
http://sites.akvotest.org/news/
http://sites.akvotest.org/blog/
