### ISSUE TITLE
Integrate RSR Results Framework view

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#381]
Context

When a partner has a detailed Results Framework setup, they would like to share this on their Akvo Site.
Eg. 
https://rsr.akvo.org/en/project/4296/#results

![screen shot 2018-02-19 at 16 27 02](https://user-images.githubusercontent.com/2675262/36385067-c3dfeb80-1591-11e8-96e6-e3a8dee71c49.png)

Problem or idea

There is no way, currently, to embed or display this on an Akvo Site.

Solution or next step

How could we solve it?

**Comment by samvthom16** [comment]
https://github.com/akvo/Akvo-Sites-2019/issues/13
