### ISSUE TITLE
Improve image quality pulled from RSR API

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Sites-ZZ-Template#383]

**Comment by Lynngre** [comment]
update template for project updates to use https://rsr.akvo.org/rest/v1/project_update/?project__partners__in=ID&format=json&image_thumb_name=big

and for projects
https://rsr.akvo.org/rest/v1/project/?format=json&primary_location__country__iso_code=gh&primary_organisation=ID&image_thumb_name=big
