### ISSUE TITLE
Get in touch button to AfriAllaince Marketplace

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#385]
Add a get in touch button to form on selected action group idea. Automails to 'action group' suggestor.

**Comment by Lynngre** [comment]
https://afrialliance.org/markets/water-solutions/

A button to send an email to the relevant person in the market needs to be added to the above page type.

- [ ] email address should be taken from details filled in on market place
- [ ] how clicks through to contact form or directly to email?

**Comment by samvthom16** [comment]
Use the following plugins:
https://wordpress.org/plugins/contact-form-7/
https://wordpress.org/plugins/contact-form-7-dynamic-text-extension/

Retrieve custom fields from the current post. Just set the custom field as the key in the shortcode.
The dynamic value input becomes: CF7_get_custom_field key=’my_custom_field’
And the tag looks like this:
[dynamictext dynamicname “CF7_get_custom_field key=’my_custom_field'”]

The dynamicname can be set as the recipient of the email.
