### ISSUE TITLE
Siteorigin: Akvo Title & Image widget

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#391]
The widget doesn't respond well with different sized images. It seems to be fixed on requiring the largest size - 3072x2304 to produce a good looking header area. 

The Siteorigin widgets are more responsive when it comes to images. Has something changed in the way media size is handled when we created our own widget?

<img width="1297" alt="screen shot 2018-03-19 at 16 36 34" src="https://user-images.githubusercontent.com/2675262/37605666-fd4af492-2b93-11e8-9f63-df3c20837dd1.png">

**Comment by samvthom16** [comment]
Solving this here:
https://github.com/akvo/akvo-siteorigin-widgets/issues
