### ISSUE TITLE
Single post widget - border

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#392]
When selecting to add a border, the border is not visible.

![screen shot 2018-04-09 at 13 37 45](https://user-images.githubusercontent.com/2675262/38495826-5e868772-3bfb-11e8-9a1e-62fbe27df8cb.png)
![screen shot 2018-04-09 at 13 39 07](https://user-images.githubusercontent.com/2675262/38495833-65feb330-3bfb-11e8-9d83-64cfe213b782.png)

**Comment by samvthom16** [comment]
@Lynngre The site origin options won't work on this widget. For them to work, the widget has to be re-written as a site origin widget.

**Comment by samvthom16** [comment]
Solved this by recreating a site origin widget for the same functionality
