### ISSUE TITLE
List option for Custom Post types

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#393]
Create option to view list instead of cards, without image similar to example for openAfrica.

![screen shot 2018-04-23 at 10 34 32](https://user-images.githubusercontent.com/2675262/39115452-f7b8eb74-46e1-11e8-8147-ea84d67f9b44.png)

![screen shot 2018-04-23 at 10 33 45](https://user-images.githubusercontent.com/2675262/39115424-e436c260-46e1-11e8-819f-b815075cff48.png)

**Comment by samvthom16** [comment]
https://washdata-sl.org/media/

**Comment by Lynngre** [comment]
Working ok.
