### ISSUE TITLE
Menu background colours not working as intended

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#404]
![screen shot 2018-06-05 at 16 58 30](https://user-images.githubusercontent.com/2675262/40984457-3f1a1f48-68e2-11e8-9459-d79cb899f509.png)

![screen shot 2018-06-05 at 17 02 44](https://user-images.githubusercontent.com/2675262/40984479-4d0eae70-68e2-11e8-8362-032150871c3b.png)

**Comment by samvthom16** [comment]
@Lynngre have patched in the fix on live as well
