### ISSUE TITLE
Upgrade PHP to 7.0

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#406]
Reason: to improve speed of Sites & ensure that the PHP version remains supported.

Look at incompatibility issues & check off before upgrading.
[report.txt](https://github.com/akvo/akvo-sites-zz-template/files/2093244/report.txt)

**Comment by samvthom16** [comment]
Checklist:
1. Datafeed plugin
2. Akvo Cards shortcode and widgets
3. Customise options
4. Site origin page builder

**Comment by Lynngre** [comment]
Upgrading to 7.0.30 instead as BBpress running on various sites is not compatible with 7.1

**Comment by Lynngre** [comment]
Even after testing, something specific to how the current Akvo Sites is setup, created an incompatibility when migrating to PHP7.  Further testing/research to be done.

**Comment by Lynngre** [comment]
Done, running PHP 7.1.2.1
