### ISSUE TITLE
Add additional function to oxfam theme

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/Akvo-Sites-ZZ-Template#411]
Hi Lynn, Sam,
Please add me to the group, I've created new feature branch but unable to push the branch upstream.
<img width="720" alt="screen shot 2018-06-25 at 01 49 46" src="https://user-images.githubusercontent.com/3245109/41821910-32b9e796-781a-11e8-9fe6-be03a2dfe950.png">

Thanks,

**Comment by samvthom16** [comment]
@dedenbangkit you have been added to the team but you would have to accept the invitation first before pushing any code.

**Comment by Lynngre** [comment]
Completed via the Custom CSS & siteorigin pagebuilder.
