### ISSUE TITLE
Pagination Akvo Cards

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#412]
When using Akvo Cards, pagination is not working correctly.
[akvo-cards type="rsr" type-text="Projects" rsr-id="keywords" posts_per_page="9" pagination="1"]

Results in no further project updates loading at the first 30, at https://watershed.nl/project-info/project-updates/ for example
<img width="1195" alt="screen shot 2018-06-25 at 13 48 59" src="https://user-images.githubusercontent.com/2675262/41848883-57cb3fc0-787f-11e8-82be-16e29ce2b30a.png">

**Comment by samvthom16** [comment]
In the admin interface of data feed options, the pagination policy has to be overridden.

For example:
page-url=next:next&page-update-check=null&limit=10 

Where limit is the number of pages it should fetch.
