### ISSUE TITLE
Akvo Card Widget - default image

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#416]
The default image (for when an RSR project has no photo or is a video), is not working for Watershed.nl.

<img width="655" alt="screen shot 2018-07-03 at 16 41 05" src="https://user-images.githubusercontent.com/2675262/42226806-2c8ac1a2-7ee0-11e8-8670-b9146f04a306.png">

**Comment by samvthom16** [comment]
Print css function combines all the css to be printed which needs to be reflected through the customize section. This framework basically helps in improving performance as it combines all the css in one place. An exception had to be created for 'background-image' style attribute to wrap the value within url(). 

Earlier: background-image: IMAGE
Which had to be changed to: background-image: url('IMAGE')
