### ISSUE TITLE
Filtering for Akvo Cards

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#418]
Figure out how to allow filtering/use filtering on Akvo Cards

**Comment by Lynngre** [comment]
related:  https://github.com/akvo/akvo-sites-zz-template/issues/410

**Comment by Lynngre** [comment]
Is it possible to use something like https://wordpress.org/plugins/beautiful-taxonomy-filters/#description or  https://wordpress.org/plugins/search-filter/ to create custom post type filtering using  shortcodes?

**Comment by Lynngre** [comment]
Seems to be working ok, but only for 'blog posts' right now?

**Comment by samvthom16** [comment]
@Lynngre I figured the issue, the filters for other post type were not activated through customize section.

**Comment by Lynngre** [comment]
Ok, that works as expected then. Thanks.
