### ISSUE TITLE
Json data plugin - refresh issue

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#425]
Something odd is happening with caching for Sites that have widgets added to their pages for displaying RSR project or update data, using the Json data plugin.

You have to manually refresh the page to see all the projects or updates.

Such as https://footballforwater.org.

Their Kenya page before I refresh

![screen shot 2018-08-28 at 13 35 47](https://user-images.githubusercontent.com/2675262/44720639-ad72dd00-aac7-11e8-9950-7cf063dba31a.png)

Their Kenya page after I refresh

![screen shot 2018-08-28 at 13 35 59](https://user-images.githubusercontent.com/2675262/44720649-b368be00-aac7-11e8-8c57-1e5934e9b1a7.png)

**Comment by Lynngre** [comment]
Still happening until refreshing pages in browser manually.


<img width="1333" alt="screen shot 2018-09-18 at 13 23 14" src="https://user-images.githubusercontent.com/2675262/45685087-89e00700-bb48-11e8-92c0-6a4ef5a69235.png">
<img width="1315" alt="screen shot 2018-09-18 at 13 23 23" src="https://user-images.githubusercontent.com/2675262/45685088-89e00700-bb48-11e8-9ecc-3fc65e6032ab.png">

after refresh:

<img width="1330" alt="screen shot 2018-09-18 at 13 23 37" src="https://user-images.githubusercontent.com/2675262/45685097-91071500-bb48-11e8-878a-17364127dc15.png">

**Comment by samvthom16** [comment]
Replacing the single widgets with the new Site Origin WIdget

**Comment by Lynngre** [comment]
Counting was being done separately. 
Replacement - will check other sites for issue.
