### ISSUE TITLE
Titles are not being displayed by default on Akvo Card widgets

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#430]
Titles are no longer being displayed by default. They are not set to be hidden under 'customize'

https://afrialliance.org/demand-driven-action-groups/
https://afrialliance.org/news/

<img width="1311" alt="screen shot 2018-10-11 at 13 04 52" src="https://user-images.githubusercontent.com/2675262/46799873-44cd8000-cd56-11e8-8783-8d7868891314.png">

<img width="1175" alt="screen shot 2018-10-11 at 13 05 32" src="https://user-images.githubusercontent.com/2675262/46799906-5d3d9a80-cd56-11e8-8712-8d77a6bf7306.png">

**Comment by Lynngre** [comment]
Looks like it's only Afrialliance.

**Comment by samvthom16** [comment]
This could be related to https://github.com/akvo/akvo-sites-2016/issues/454

**Comment by samvthom16** [comment]
This is has been solved here https://github.com/akvo/akvo-sites-2016/issues/477
