### ISSUE TITLE
Widgets missing from 'customise' 

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#45]
The ability to add widgets from the customise area of the Theme has disappeared since the latest Akvopedia Widget code was added.

**Comment by AndreasJonsson** [comment]
Aktually, the problem is with the data-feed plugin, because after deactivating it the widgets panel reappear.

**Comment by Lynngre** [comment]
Ah ok great please check if you can fix it.

**Comment by AndreasJonsson** [comment]
Fixed by adding exception handling to the data feed widget.

**Comment by Lynngre** [comment]
@AndreasJonsson could you take another look at this?  The Exception handling hasn't fixed the issue. the widget option under 'customise' still disappears when 'data feed' plugin is activated.
![screen shot 2015-12-08 at 11 00 17](https://cloud.githubusercontent.com/assets/2675262/11653068/c9fca636-9d9b-11e5-8971-61df1614e114.png)
![screen shot 2015-12-08 at 11 00 38](https://cloud.githubusercontent.com/assets/2675262/11653067/c9fad266-9d9b-11e5-891e-b79e62b46cbf.png)

**Comment by Lynngre** [comment]
This is, however, fixed on the test server with the code you added. Really odd as we've got the same code running on live now.

**Comment by AndreasJonsson** [comment]
It's going to be really hard for me to figure out what the problem is if it doesn't appear on the test server.  Are you sure you've got the same version on the live server?

**Comment by Lynngre** [comment]
Ok let me do some further investigation.

**Comment by Lynngre** [comment]
#45 fixed & closed
