### ISSUE TITLE
Data feed - RSR API data is not appearing in cards 

### ISSUE THREAD

**Issue by Lynngre** [akvo/Akvo-Sites-ZZ-Template#458]
API call is tested and correct but data is not being 'called' into widget by Sites theme.

**Comment by Lynngre** [comment]
Example:  https://drydev.akvoapp.org/rest/v1/project_update/?format=json&project=3763&amp;image_thumb_name=big

https://drydev.org/iframe-test/


https://washalliance.akvoapp.org/rest/v1/project_update/?format=json&project=6892&amp;image_thumb_name=big

https://wash-alliance.org/

**Comment by Lynngre** [comment]
widget.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
    at widget.js:1 . is the console error received.

Confirmed that RSR API has not changed.

**Comment by Lynngre** [comment]
This includes the use of the Akvo Card multiple or single.

**Comment by Lynngre** [comment]
Upon further investigation looks like it may be RSR migration related. API call comes back with 503 when run via plugin (text/html is sent back instead of JSON).

**Comment by Lynngre** [comment]
After digging deeper with the platform & RSR teams it looks like the issue is down to the fact that no matter what the user sets in the  data feed settings or customisation area, the data feed plugin still makes all API calls as http instead of https which leads to a redirect of 301 which is text/html so the plugin doesn't deal with the redirect.

**Comment by samvthom16** [comment]
The issue has been with the hosting and DNS Zone changes that were not being reflected.

**Comment by Lynngre** [comment]
Siteground hosting finally found the issue is down to how their DNS Zones are setup, once new RSR ip address was manually forced the API was accessible as normal.
