### ISSUE TITLE
Akvopedia dependency

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#57]
When Akvopedia.org is unavailable/down and an Akvo Site is making use of the widget/plugin, the site FIRST tries to find akvopedia.org - which means it takes a very long time to load the actual homepage, or any page on the site.

Akvopedia being down should not affect Akvo sites.

Would you check this please @AndreasJonsson ?

**Comment by Lynngre** [comment]
@AndreasJonsson could you check the test server sites.akvotest.org please?  We're in process of checking code for deploying to the live server but I noticed the Akvopedia widget/gadget is not loading the pages anymore. The permalinks under 'Akvopedia' in the menu are 404s & the widgets added to homepage for example, don't load. This is the only update/change to the Akvopedia widget since last update.

**Comment by AndreasJonsson** [comment]
When loaded asyncronously, the akvopedia gadget jQuery plugin may be registered at the skin bundled version of jQuery, while the initialization code references the Wordpress bundled version. #66
