### ISSUE TITLE
Breadcrumb extra layers added

### ISSUE THREAD

**Issue by lauraroverts** [akvo/Akvo-Sites-ZZ-Template#6]
Extra layers are added to the breadcrumb navigation. 
E.g. if you look at http://unicefpacificwash.org/media/, the breadcrumb navigation shows an extra layer 'news'.

![screen shot 2015-08-27 at 10 15 03](https://cloud.githubusercontent.com/assets/4179989/9515838/8b481a3a-4ca4-11e5-9285-cab2f36e5c3d.png)

According to Daan (ZZ) it might have something to do with the network settings that overrule.

**Comment by Lynngre** [comment]
@lauraroverts looking at this issue, but currently can't see any reason why this is happening :-( Will keep at it.

**Comment by lauraroverts** [comment]
maybe Anna-Marthe can check it again. She brought up this issue.

**Comment by Lynngre** [comment]
FIXED! in the network/overall settings we needed to 'deselect' a root page for each submenu item. 
![setting_breadcrumbs](https://cloud.githubusercontent.com/assets/2675262/10189307/db9e4a32-6765-11e5-94bc-cff33cc6f5e6.png)

**Comment by Lynngre** [comment]
Fixed.
