### ISSUE TITLE
The skin bundles its own version of jQuery

### ISSUE THREAD

**Issue by AndreasJonsson** [akvo/akvo-sites-zz-template#66]
The wordpress bundled version 1.11.3 is the expected one.  But the theme also loads 2.2.0 (which is packed in the file http://sites.akvotest.org/wp-content/themes/akvo-sites/dist/scripts/main-5f54cbdb.js).

So, initially, the variable jQuery is bound to the 1.11.3 instance, but later it will be bound to the 2.2.0 instance.

**Comment by AndreasJonsson** [comment]
Related to #57.

**Comment by Lynngre** [comment]
@AndreasJonsson thanks for the quick response on this.  I've uploaded this version of the plugin but it hasn't resulted in a fix.  https://github.com/akvo/akvo-sites-zz-template/commit/a6affd15a46d894605b620aeed9a451765535544

Akvopedia just doesn't load.

The 404s seem to be cleared when I update the permalinks.

**Comment by Lynngre** [comment]
Akvopedia seems to load correctly on Chrome/Safari some of the time but not consistently whereas they don't load on FF at all.

**Comment by Lynngre** [comment]
Oddly, I can now see the Akvopedia widget contents 
![screen shot 2016-01-12 at 12 41 09](https://cloud.githubusercontent.com/assets/2675262/12262722/e255b444-b929-11e5-8469-73ad74be035d.png)
in the 'customize' area of the theme but it still doesn't display on the sites.akvotest.org homepage

**Comment by Lynngre** [comment]
I asked one of our developers here to have a quick look to ensure it wasn't just something I was missing and he found the following:

"It seems like the scripts are loaded with both the "defer" and "async" attributes. My understanding was that typically only one of these attributes is used but Andreas may know more."

"Another piece of information that may be useful - when the plugin loads fails to load the akvopedia content, it seems to inject a <noscript> tag with an iframe inside it instead. This tag is not injected when the plugin loads the akvopedia content correctly. That seems to be injected at this point: https://github.com/akvo/akvo-sites-zz-template/blob/a6affd15a46d894605b620aeed9a451765535544/code/wp-content/plugins/akvopedia-widget/src/AkvopediaWidget/Gadget/AkvopediaGadget.php#L75-L80   that may or may not be helpful in debugging this problem"

**Comment by AndreasJonsson** [comment]
I have not fixed this issue (two differen jQuery instances), so the AkvopediaWidget is expected to still not work.

It is legal to use both "defer" and "async".  (If you remove "defer", I'm guessing the gadget will work if the script is already cached but not when it isn't.  But it isn't the gadget that is the problem.)

Contents of noscript tags are ignored if javascript is available and enabled in the browser disregarding of whether the script successfully runs or not.

**Comment by Lynngre** [comment]
@AndreasJonsson ok, so what was the change/commit you added for?  

Also, how do you suggest we move forward to get this working?

**Comment by AndreasJonsson** [comment]
My recommendation is to remove jQuery from the skin.

**Comment by Lynngre** [comment]
@AndreasJonsson can you check what it's being used for exactly before we remove it?  I'm guessing it's running there (was that a higher version?) for a reason.  We need to know what will break if we make that change.

**Comment by AndreasJonsson** [comment]
The main difference between jQuery 1.x and 2.x is that in 2.x they have dropped support for older browsers to make it smaller and faster.  Otherwise I believe the versions are compatible.  So I think it is unlikely that something would break by removing the 2.2 instance.

**Comment by Lynngre** [comment]
@tlandn Lan could you have a look at this issue for us?  The theme seems to use it's own jquery instead of using the version that ships with Wordpress.  Could you look at what the impact could be on the theme if we use the wordpress version instead & also how much work it would be (time wise) to fix?

**Comment by tlandn** [comment]
@Lynngre Done
