### ISSUE TITLE
Add widgets to site header

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#67]
@tlandn please could you look at allowing the addition of adding a widget to the the header for each site?

We would like the option of adding the Prisna Google translate widget below the 'search' area in the header via the theme customise area.

Could you let me know how many hours you think it would take please?

**Comment by tlandn** [comment]
@Lynngre Done

**Comment by Lynngre** [comment]
@tlandn could you check why part of the widget overlaps the 'search' box please?

![screen shot 2016-02-11 at 12 49 53](https://cloud.githubusercontent.com/assets/2675262/12975702/17e245fe-d0be-11e5-8b51-e04955fd8c1a.png)

**Comment by tlandn** [comment]
Hi @Lynngre , the above widget is existed before I do the work, anyway I removed it. Please see http://sites.akvotest.org . Thanks.

**Comment by Lynngre** [comment]
Fantastic, thanks.
