### ISSUE TITLE
Header doesn't fit in box

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites-zz-template#75]
In the screenshot below you can see that the word 'testimonal' doesn't fit next to the date and is automatically placed in the next line. Screenshot taken at http://akvosites.akvo.org

![akvo_sites_ _an_interactive_preview](https://cloud.githubusercontent.com/assets/4179989/13598748/da093e06-e51f-11e5-8ee0-d9db4a8d24b3.png)

**Comment by Lynngre** [comment]
No longer an issue on new theme.
