### ISSUE TITLE
Active page - menu item

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#82]
User needs to be able to set the 'active page' colour highlighting the item in the menu via the theme customiser.

Currently it's set to some odd  #green/blue colour which is completely unrelated to the colours chosen via the theme customiser.

**Comment by Lynngre** [comment]
![screen shot 2016-03-21 at 12 17 12](https://cloud.githubusercontent.com/assets/2675262/13917543/dc8238d0-ef61-11e5-8134-3a6492391302.png)

**Comment by samvthom16** [comment]
This has been fixed in the new theme.

**Comment by Lynngre** [comment]
is there an easy way to fix this in the old theme too?  For those sites not moving?

**Comment by Lynngre** [comment]
#82 fixed & closed
