### ISSUE TITLE
Media page rows

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#83]
The widgets are not appearing in rows correctly after 2nd row.

The formatting after row 2 is completely out of line & widgets are scattered randomly.

For example.  http://wash-mali.org/media/  (scroll down)

![screen shot 2016-03-21 at 12 31 37](https://cloud.githubusercontent.com/assets/2675262/13917639/64f1ed0a-ef62-11e5-8b26-c8b45c59f013.png)

**Comment by samvthom16** [comment]
Please share the link

**Comment by Lynngre** [comment]
@samvthom16 we should also set these to all be the same size.

**Comment by samvthom16** [comment]
This page will need redesigning using a grid or a masonry layout

**Comment by Lynngre** [comment]
Please go ahead with that.

**Comment by Lynngre** [comment]
@samvthom16 any update on this?

**Comment by Lynngre** [comment]
@samvthom16 this needs to be done regardless of our new theme

**Comment by Lynngre** [comment]
New base theme doesn't have this issue. This won't be fixed on ZZ theme.
