### ISSUE TITLE
Carousel: Interval

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#85]
Add an option to the 'Carousel' admin area under 'customise' for theme for a user to decide on the auto scroll interval for the carousel on the homepage (include the option to switch of auto scroll too).
Ensure that this can be individually set for sites.  The default should be current setting.

Current setting in carousel.js: 

  Carousel.DEFAULTS = {
    interval: 5000

**Comment by Lynngre** [comment]
@samvthom16 any update on making this something we can change on old & new theme?

**Comment by samvthom16** [comment]
Custom carousel interval can be added like this:
[akvo-carousel interval=3000]

**Comment by samvthom16** [comment]
Changed from the shortcode attributes to customise option.

**Comment by Lynngre** [comment]
#85 fixed & closed on new theme
