### ISSUE TITLE
Theme menu responsiveness

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites-zz-template#88]
When the screen is narrowed, the menu items stack behind the carousel image.

As per example:
![screen shot 2016-04-18 at 15 05 24](https://cloud.githubusercontent.com/assets/2675262/14605103/56178d50-0577-11e6-80fc-ebbcf07bc7d7.png)

Usually looks like this:

![screen shot 2016-04-18 at 15 09 27](https://cloud.githubusercontent.com/assets/2675262/14605162/9bd4ff08-0577-11e6-9022-ea21605026ed.png)

**Comment by samvthom16** [comment]
Please share the link here

**Comment by Lynngre** [comment]
@samvthom16 this is for any of the sites on sites.akvo.org but the one in the example is afrialliance.org

**Comment by samvthom16** [comment]
There are two many menu items stacked in a single row.

**Comment by Lynngre** [comment]
#88 fixed & closed
