### ISSUE TITLE
Media library post images too large

### ISSUE THREAD

**Issue by lauraroverts** [akvo/Akvo-Sites-ZZ-Template#9]
In the media library website visitors are able to download documents that have been uploaded here. For example in http://unicefpacificwash.org/media/. The purpose of this page is to download documents. 

If I click on an item to download, a lot of attention is given to the image and the download button is therefore somewhat hidden. Can i set a featured image only to appear as a small image in the box on the media library overview page, instead of also as a full size image on the post?

Daan (ZZ) is looking into this.

**Comment by Lynngre** [comment]
Looks fixed to me, @lauraroverts could you check?

**Comment by lauraroverts** [comment]
confirmed
